# Start with neofetch
#neofetch

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/popey/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="spaceship"

# LOAD ZSH THEME POWERLEVEL10K
#source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=6

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
#ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
#    sudo
    colored-man-pages
#    zsh-syntax-highlighting
#    zsh-autosuggestions
#    command-not-found
#    archlinux
#    pip
#    python
#    django
#    systemd
#    common-aliases
    k
)

source $ZSH/oh-my-zsh.sh

#################################################
#           SPACESHIP Configure                 #
#################################################

# Config prompt (right & left) [SPACESHIP]
SPACESHIP_PROMPT_ORDER=(
    user
    host
    dir
    git
    venv
    char
)

SPACESHIP_RPROMPT_ORDER=(
    jobs
    exit_code
    exec_time
    time
)

# Config prompt (color, format, ...) [SPACESHIP]

SPACESHIP_PROMPT_ADD_NEWLINE=false

# TIME
SPACESHIP_TIME_SHOW=true
#SPACESHIP_TIME_12HR=true
SPACESHIP_TIME_COLOR="#4e4e4e"
SPACESHIP_TIME_PREFIX=""

# USER
SPACESHIP_USER_SHOW=always
SPACESHIP_USER_COLOR="#008787"
SPACESHIP_USER_SUFFIX=""

# HOST
SPACESHIP_HOST_SHOW=always
SPACESHIP_HOST_PREFIX="@"
SPACESHIP_HOST_SUFFIX=""
#SPACESHIP_HOST_COLOR="#4e4e4e"
SPACESHIP_HOST_COLOR="#87875f"

# DIRECTORY
SPACESHIP_DIR_TRUNC=0
SPACESHIP_DIR_PREFIX=":"
SPACESHIP_DIR_COLOR="#005f5f"
#SPACESHIP_DIR_COLOR="#87875f"

# EXECUTION TIME
SPACESHIP_EXEC_TIME_SHOW=true
SPACESHIP_EXEC_TIME_COLOR="#87875f"
SPACESHIP_EXEC_TIME_PREFIX=""

# ERROR CODE / EXIT CODE
SPACESHIP_EXIT_CODE_SHOW=true

# JOBS
SPACESHIP_JOBS_COLOR="#87875f"
SPACESHIP_JOBS_AMOUNT_THRESHOLD=0
SPACESHIP_JOBS_AMOUNT_PREFIX=" "
SPACESHIP_JOBS_SYMBOL="ϣ"

# GIT
# git branch
#SPACESHIP_GIT_BRANCH_COLOR="#008787"
# git status
SPACESHIP_GIT_STATUS_COLOR="#008700"

# CHAR
SPACESHIP_CHAR_SYMBOL="$"
SPACESHIP_CHAR_COLOR_SUCCESS="#87875f"
SPACESHIP_CHAR_COLOR_FAILURE="#87875f"
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_PREFIX=""

#################################################

export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# set environment variable editor
export EDITOR='vim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Custom aliases are in another file
source $HOME/.aliases

# Set default font size for urxvt
term_size 15
